// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  service_hero: dynamic(() => import("./BlockHero")),
};
